# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /home/jess/data/wild_deserts/Beyond the Fence- Tagged/trial_5  # dataset root dir
train: training.txt  # train images (relative to 'path')
val: validation.txt  # val images (relative to 'path')
test:  # test images (optional)

# Classes
names:
  0: Red Kangaroo
  1: Western Grey Kangaroo
  2: Dingo
  3: Rabbit
  4: Cat
  5: Small mammal
  6: Goat
  7: Pig
  8: Euro
  9: Fox
  10: Echidna


# Download script/URL (optional)
download: https://ultralytics.com/assets/trial_5.zip
